/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactDetails {
  'email' : string,
  'address' : string,
  'phone' : string,
  'displayMap' : boolean,
  'mapEmbed' : string,
}
export interface ContentSection {
  'id' : string,
  'title' : string,
  'isPublished' : boolean,
  'body' : string,
}
export interface Enquiry {
  'id' : string,
  'subject' : string,
  'enquiryType' : string,
  'name' : string,
  'submittedAt' : Time,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : string,
  'title' : string,
  'isActive' : boolean,
  'category' : string,
  'image' : ExternalBlob,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createContentSection' : ActorMethod<[ContentSection], undefined>,
  'createGalleryItem' : ActorMethod<[GalleryItem], undefined>,
  'deleteContentSection' : ActorMethod<[string], undefined>,
  'deleteEnquiry' : ActorMethod<[string], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'getAllContentSections' : ActorMethod<[], Array<ContentSection>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactDetails' : ActorMethod<[], ContactDetails>,
  'getContentSection' : ActorMethod<[string], ContentSection>,
  'getGalleryItemsByCategory' : ActorMethod<[string], Array<GalleryItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markEnquiryAsRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEnquiry' : ActorMethod<[Enquiry], undefined>,
  'toggleMapDisplay' : ActorMethod<[], undefined>,
  'updateContactDetails' : ActorMethod<[ContactDetails], undefined>,
  'updateContentSection' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'updateGalleryItem' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'updateMapEmbed' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];